<html>
    <head>
        <meta charset="utf-8">
        <title>Zeipt App API</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link href="//fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css">
        <style>
            body {
                margin: 43px 0 0 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: left;
                color: black;
                font-size: 18px;
                background-color: #F1F5FA;
            }

            .container {
                padding: 10px 15px 80px;
                max-width: 1200px;
                margin: 0 auto;
            }

            .banner {
                position: fixed;
                display: flex;
                background-color: #0F2841;
                left: 0;
                right: 0;
                height: 43px;
                top: 0;
                flex-direction: row;
                align-items: center;
                overflow: hidden;
            }

            .banner img {
                width: 30px;
                display: table-cell;
                margin: auto;
            }

            .banner-content {
                vertical-align: middle;
                display: table;
                width: 100%;
                padding: 0 10px;
            }

            .row {
                width: 100%;
                height: 100%;
                display: table-row;
            }

            .column {
                display: table-cell;
                width: 33.33%;
                vertical-align: middle;
                position: relative;
            }

            .column.left {
                text-align: left;
            }

            .column.center {
                text-align: center;
            }

            .column.right {
                text-align: right;
            }

            .column.left img {
                float: left;
                height: 30px;
                width: unset;
            }

            .column.center img {
                box-shadow: 0 0 50px #3CBF71;
                border-radius: 100px;
            }

            .approve-form {
                text-align: center;
                position: fixed;
                bottom: 0px;
                left: 0;
                right: 0;
                padding: 20px;
                background-color: rgba(242, 245, 251, 0.9);
                background: linear-gradient(to bottom, rgba(242, 245, 251, 0), rgba(242, 245, 251, 1));
            }

            .terms-approve {
                background-color: #3CBF71;
                color: white;
                border-radius: 2px;
                cursor: pointer;
                transition: all .2s;
                font-size: 16px;
                margin: auto;
                width: 100%;
                border: none;
                padding: 20px;
            }

            .terms-approve.disabled {
                color: #585858;
                background-color: buttonface;
            }

            .error {
                background-color: rgb(191, 60, 60);
                border-radius: 500px;
                text-align: center;
                width: 200px;
                height: 200px;
                margin: auto;
                margin-top: 40px;
                position: relative;
            }

            .error h2 {
                position: absolute;
                left: 0;
                right: 0;
                top: 50%;
                transform: translateY(-50%);
                margin: auto;
            }
            h3.success-note {
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="banner">
                <div class="banner-content">
                    <div class="row">
                        <div class="column left">
                            <img src="<?= $assetsUrl ?>/img/zeipt.png">
                        </div>
                        <div class="column center">
                            <img src="<?= $assetsUrl ?>/img/receiptguy.svg">
                        </div>
                        <div class="column right">

                        </div>
                    </div>
                </div>
            </div>
            <div class="error">
                <h2>error...</h2>
            </div>
            <h3 class="success-note">There was an error trying to register your card. <br> Please try again.</h3>
        </div>
    </body>
</html>