<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Card registered</title>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
                background-color:whitesmoke;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 50px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Card has been registered, you can now close this page. It will close automatically in 3 seconds</h1>
        <script>
            $(document).ready(function() {
                setTimeout(function(){
                    window.close();
                }, 3000);
            });
        </script>
    </body>
</html>
